{%include file="header.phtml"%}

<div id="container">
    <div id="body">
        <div class="label">
                <div style="background:#69ac16;text-align:center;font-size:xx-small;color:#FFF">
                        <table><tr><td></td></tr></table>
                        自分のキャラを決めよう！
                        <table><tr><td></td></tr></table>
                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/label_line.gif" width="100%" height="10px" />
                </div>
        </div>
        <form action='{% "$baseUrl/firstlogin/login"|mixiurl %}' method="post">
        <div class="restaurant">
                <div style="text-align:left;font-size:x-small">
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/npc.gif" style="float:left;margin:5px" align="left" />
                        自分のキャラクターを決めよう！{% emoji code="F995" %}<br />
                        変更は出来ないから気をつけてね{% emoji code="F99B" %}
                </div>
                <div style="text-align:center;font-size:xx-small;background:#69ac16;clear:both;color:#FFF" clear="all">
                        キャラクター
                </div>
                <div style="text-align:center;font-size:xx-small">
                        [{% if $chara== "m" %}男の子{%else%}<a href='{% "$baseUrl/firstlogin/characterselect/CF_chara/m"|mixiurl %}'>男の子</a>{%/if%}|{% if $chara== "f" %}女の子{%else%}<a href='{% "$baseUrl/firstlogin/characterselect/CF_chara/f"|mixiurl %}'>女の子</a>{%/if%}]
                </div>
                <div style="text-align:center;">
                        <table align="center">
                                <tr>
                                        <td><div style="text-align:center;font-size:xx-small"><img src="{%$staticUrl%}/apps/restaurant/mobile/img/character/{%$chara%}1.gif" width="48" /><br /><input type="radio" checked name="character" value="{%$chara%}1" /></div></td>
                                        <td><div style="text-align:center;font-size:xx-small"><img src="{%$staticUrl%}/apps/restaurant/mobile/img/character/{%$chara%}2.gif" width="48" /><br /><input type="radio" name="character" value="{%$chara%}2" /></div></td>
                                        <td><div style="text-align:center;font-size:xx-small"><img src="{%$staticUrl%}/apps/restaurant/mobile/img/character/{%$chara%}3.gif" width="48" /><br /><input type="radio" name="character" value="{%$chara%}3" /></div></td>
                                        <td><div style="text-align:center;font-size:xx-small"><img src="{%$staticUrl%}/apps/restaurant/mobile/img/character/{%$chara%}4.gif" width="48" /><br /><input type="radio" name="character" value="{%$chara%}4" /></div></td>
                                        <td><div style="text-align:center;font-size:xx-small"><img src="{%$staticUrl%}/apps/restaurant/mobile/img/character/{%$chara%}5.gif" width="48" /><br /><input type="radio" name="character" value="{%$chara%}5" /></div></td>
                                </tr>
                        </table>
                </div>
                <div style="text-align:center;font-size:xx-small;background:#69ac16;clear:both;color:#FFF" clear="all">
                        レストランの名前
                </div>
                {% if $error %}
					<div class="caution" style="color:#cc0000;">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						{% emoji code="F9DC" %}入力エラー:<br />
						{% if $error == 1 %}
							･入力欄が未入力です<br />
						{% elseif $error == 2 %}
							･2文字以上～13文字以内で入力してください<br />
						{% /if %}
					</div><!--/.caution-->
				{% /if %}
                <div style="text-align:left;font-size:xx-small">
                        ※全角2文字以上～13文字<br />
                        <div style="text-align:center;font-size:xx-small">
                                <input type="text" name="txtName" /><br />
                                <input type="submit" value="次へ" />
                        </div>
                </div>
        </div><!--/.restaurant-->
        </form>
        <table><tr><td></td></tr></table>
        <table><tr><td></td></tr></table>
    </div><!--/#body-->
</div><!--/#continar-->

{%include file="footer.phtml"%}