{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div id="menu_list">
                        <div style="background:#69ac16;text-align:center;font-size:xx-small;color:#FFF">
                                フレンドメニュー
                        </div>
                        <div style="text-align:center;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/food/{%$recipeId%}.gif" />
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:left;font-size:xx-small">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/character/{%$userProfile.character%}.gif" style="float:left;margin-right:5px" align="left" />
                                フォアグラと焼き加減が絶妙！！
                        </div>
                        <div style="text-align:left;font-size:xx-small">
                                お腹が膨れました。<br />
                                空腹度:★☆☆☆☆
                        </div>
                        <div style="text-align:center;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/dotted.gif" width="240px" height="1px" style="margin-top:3px;margin-bottom:3px;" />
                        </div>
                        <div style="text-align:left;font-size:xx-small">
                                <span style="color:#F00">【ﾚｼﾋﾟ習得!】</span><br />
                                『タルタルステーキ』を習得しました!<br />
                                <a href='{% "$baseUrl/firstlogin/todaygetrecipe/recipeId/$recipeId"|mixiurl %}'>早速作ってみる</a>
                        </div>
                                                
                        <table><tr><td></td></tr></table>
                </div><!--/#menu_list-->
        </div>
</div>

{%include file="footer.phtml"%}