{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div style="background:#69ac16;text-align:center;font-size:xx-small;color:#FFF">
                        ○○さんの今日のﾒﾆｭｰ
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/label_line.gif" width="100%" height="10px" />
                </div>
                <table><tr><td></td></tr></table>
                <div id="friend_food">
                        <table><tr><td></td></tr></table>
                        <div class="cook_sum" style="width:240;margin:auto;text-align:center;background:#">
                                <div style="text-align:left;font-size:xx-small">
                                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/food/d01.gif" width="60" style="border:1px;border-color:#CCC;border-style:solid;margin:5px;float:left" align="left" />
                                ペペロンチーノ<br />
                                料理ﾚﾍﾞﾙ:★★☆☆☆<br />
                                ジャンル:パスタ<br />
                                コスト:150<br />
                                </div>
                                <div style="text-align:right;font-size:xx-small">
                                        <a href="npc_friend_food_confirm.php">これを食べる</a>
                                </div>
                        </div>
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/green_line.gif" width="100%" height="2px" style="margin-top:3px;margin-bottom:3px" />
                        <div class="cook_sum" style="width:240;margin:auto;text-align:center;background:#">
                                <div style="text-align:left;font-size:xx-small">
                                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/food/d01.gif" width="60" style="border:1px;border-color:#CCC;border-style:solid;margin:5px;float:left" align="left" />
                                ペペロンチーノ<br />
                                料理ﾚﾍﾞﾙ:★★☆☆☆<br />
                                ジャンル:パスタ<br />
                                コスト:150<br />
                                </div>
                                <div style="text-align:right;font-size:xx-small">
                                        <a href="npc_friend_food_confirm.php">これを食べる</a>
                                </div>
                        </div>
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/green_line.gif" width="100%" height="2px" style="margin-top:3px;margin-bottom:3px" />
                        <div class="cook_sum" style="width:240;margin:auto;text-align:center;background:#">
                                <div style="text-align:left;font-size:xx-small">
                                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/food/d01.gif" width="60" style="border:1px;border-color:#CCC;border-style:solid;margin:5px;float:left" align="left" />
                                ペペロンチーノ<br />
                                料理ﾚﾍﾞﾙ:★★☆☆☆<br />
                                ジャンル:パスタ<br />
                                コスト:150<br />
                                </div>
                                <div style="text-align:right;font-size:xx-small">
                                        <a href="npc_friend_food_confirm.php">これを食べる</a>
                                </div>
                        </div>
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/green_line.gif" width="100%" height="2px" style="margin-top:3px;margin-bottom:3px" />
                </div><!--/#menu_list-->
        </div>
</div>

{%include file="footer.phtml"%}