{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div id="cook_complete">
                        <div style="font-size:x-small;background:#f6f6f6;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/h.gif" width="5px" height="17px" style="float:left;margin-right:2px" align="left" />
                                今日のメニュー完成！
                                <div style="clear:both;" clear="all">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/line.gif" width="100%" height="1px" />
                                </div>
                        </div>
                        <div style="text-align:left;font-size:x-small">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/npc.gif" style="float:left;margin:5px" align="left" />
                                おめでとう{% emoji code="F99F" %}ﾒﾆｭｰが完成したね{% emoji code="F9A7" %}<br />
                                次は料理の材料を買いに行こう{% emoji code="F89F" %}<br />
                                材料がある間は料理を作れるよ{% emoji code="F995" %}<br />
                                切らさないようにしないとね{% emoji code="F99F" %}
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:center">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/kanban.jpg" width="100" />
                        </div>
                        <div style="text-align:center;font-size:xx-small">
                                <a href='{% "$baseUrl/firstlogin/todayshoppingcomplete"|mixiurl %}'>材料の買い出しに行く</a>
                        </div>
                        <table><tr><td></td></tr></table>
                </div><!--/#cook_complete-->
        </div>
</div>

{%include file="footer.phtml"%}