{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div id="cook_complete">
                        <div style="font-size:x-small;background:#f6f6f6;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/h.gif" width="5px" height="17px" style="float:left;margin-right:2px" align="left" />
                                本日の材料GET！
                                <div style="clear:both;" clear="all">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/line.gif" width="100%" height="1px" />
                                </div>
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:left;font-size:x-small">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/npc.gif" style="float:left;margin:5px" align="left" />
                                これで材料も揃っていよいよOPENだね{% emoji code="F9CF" %}<br />
                                じゃあ、お祝いも兼ねて私のお店においでよ{% emoji code="F99B" %}<br />
                                ご馳走しちゃうよ{% emoji code="F994" %}
                        </div>
                        <div style="text-align:center;font-size:xx-small">
                                <a href='{% "$baseUrl/firstlogin/npcfriend"|mixiurl %}'>○○さんの店へ</a>
                        </div>
                        <table><tr><td></td></tr></table>
                </div><!--/#cook_complete-->
        </div>
</div>

{%include file="footer.phtml"%}