{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div id="menu_list">
                        <div style="background:#69ac16;text-align:center;font-size:xx-small;color:#FFF">
                                祝ﾚｽﾄﾗﾝｵｰﾅｰ
                        </div>
                        <div style="text-align:left;font-size:x-small">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/npc.gif" style="float:left;margin:5px" align="left" />
                                新しいﾚｼﾋﾟも思いついたんだね☆<br />
                                将来有望なｵｰﾅｰｼｪﾌだね！<br />
                                今後は私もあなたのｶﾌｪの一人のお客として通わせてもらうね{% emoji code="F99F" %}<br />
                                お互い頑張ろうね{% emoji code="F995" %}
                        </div>
                        <div style="text-align:center;font-size:xx-small;clear:both" clear="all">
                                <a href='{% "$baseUrl/restaurant"|mixiurl %}'>自分のカフェに戻る</a>
                        </div>
                        <table><tr><td></td></tr></table>
                </div><!--/#menu_list-->
        </div>
</div>

{%include file="footer.phtml"%}