{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div id="menu_list">
                        <div style="background:#69ac16;text-align:center;font-size:xx-small;color:#FFF">
                                料理の習得
                        </div>
                        <div style="text-align:center;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/cook_01.gif" />
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:center;font-size:xx-small">
                                <a href='{% "$baseUrl/firstlogin/todaygetrecipe02/recipeId/$recipeId"|mixiurl %}' accesskey="5">作る</a>
                        </div>
                        <table><tr><td></td></tr></table>
                </div><!--/#menu_list-->
        </div>
</div>

{%include file="footer.phtml"%}