{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div id="menu_list">
                        <div style="font-size:x-small;background:#f6f6f6;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/h.gif" width="5px" height="17px" style="float:left;margin-right:2px" align="left" />
                                今日のメニュー
                                <div style="clear:both;" clear="all">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/line.gif" width="100%" height="1px" />
                                </div>
                        </div>
                        <div style="text-align:left;font-size:x-small">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/npc.gif" style="float:left;margin:5px" align="left" />
                                とろとろのオムレツはとっても美味しいよね{% emoji code="F994" %}<br />
                                私も大好きなんだー{% emoji code="F9CF" %}
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:center;font-size:xx-small;background:#69ac16;clear:both;color:#FFF" clear="all">
                                今日のﾒﾆｭｰ
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:left;font-size:xx-small">
                                前菜:プレーンオムレツ
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="clear:both" clear="all">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/green_line.gif" width="100%" height="2px" style="margin-top:3px;margin-bottom:3px" />
                        </div>
                        <div style="text-align:center;font-size:x-small">
                                <a href='{% "$baseUrl/firstlogin/todaycookcomplete"|mixiurl %}'>これでOK！</a>
                        </div>



                </div><!--/#menu_list-->
        </div>
</div>

{%include file="footer.phtml"%}