{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div id="menu_list">
                        <div class="label">
                                <div style="background:#69ac16;text-align:center;font-size:xx-small;color:#FFF">
                                        ISU
                                </div>
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:center;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/dotted.gif" width="240px" height="1px" style="margin-top:3px;margin-bottom:3px;" />
                        </div>
                        <div style="text-align:center;font-size:xx-small">
                                購入しました。
                        </div>
                        <div style="text-align:center;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/dotted.gif" width="240px" height="1px" style="margin-top:3px;margin-bottom:3px;" />
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:center;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/decoration/14.gif" />
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:center;font-size:xx-small">
                                ISU<br />
                                価格:2000元<br />
                                ｵｰｿﾄﾞｯｸｽなｲｽ｡かなり丈夫で開店したばかりのお店には重宝される。
                        </div>
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/green_line.gif" width="100%" height="2px" style="margin-top:3px;margin-bottom:3px" />
                        <div style="text-align:center;font-size:xx-small">
                                <a href="deco_setting.swf.php">早速設置する</a> 
                                <a href='{% "$baseUrl/shop/decoration"|mixiurl %}'>ｼｮｯﾌﾟに戻る</a>
                        </div>
                        <table><tr><td></td></tr></table>
                </div><!--/#menu_list-->
        </div>
</div>

{%include file="footer.phtml"%}