{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div class="label">
                        <div style="background:#69ac16;text-align:center;font-size:xx-small;color:#FFF">
                                <table><tr><td></td></tr></table>
                                ｼｮｯﾌﾟ一覧
                                <table><tr><td></td></tr></table>
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/label_line.gif" width="100%" height="10px" />
                        </div>
                </div>
                <table><tr><td></td></tr></table>
                <div id="shop_list">
                        <div style="text-align:left;font-size:xx-small">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/decoration/14.gif" style="float:left;margin:5px" align="left" />
                                <a href='{% "$baseUrl/shop/decoration"|mixiurl %}'>店舗ｺｰﾃﾞｨﾈｲﾄ</a><br />
                                ﾚｽﾄﾗﾝ・ｶﾌｪのｲﾝﾃﾘｱｺｰﾃﾞｨﾈｲﾄ専門店
                        </div>
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/green_line.gif" width="100%" height="2px" style="margin-top:3px;margin-bottom:3px" />
                        <div style="text-align:left;font-size:xx-small">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/decoration/14.gif" style="float:left;margin:5px" align="left" />
                                <a href='{% "$baseUrl/shop/item"|mixiurl %}'>ｱｲﾃﾑｼｮｯﾌﾟ</a><br />
                                便利なｱｲﾃﾑはこちらから
                        </div>
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/green_line.gif" width="100%" height="2px" style="margin-top:3px;margin-bottom:3px" />
                        <div style="text-align:left;font-size:xx-small">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/decoration/14.gif" style="float:left;margin:5px" align="left" />
                                ﾌﾞﾃｨｯｸ<br />
                                ※近日OPEN
                        </div>
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/green_line.gif" width="100%" height="2px" style="margin-top:3px;margin-bottom:3px" />
                        <div style="text-align:left;font-size:xx-small">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/decoration/14.gif" style="float:left;margin:5px" align="left" />
                                ｱﾊﾞﾀｰｼｮｯﾌﾟ<br />
                                ※近日OPEN
                        </div>
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/green_line.gif" width="100%" height="2px" style="margin-top:3px;margin-bottom:3px" />
                </div><!--/#shop_list-->
        </div>
</div>

{%include file="footer.phtml"%}