{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div id="menu_list">
                        <div class="label">
                            <div style="background:#69ac16;text-align:center;font-size:xx-small;color:#FFF">
                                {%$item.name%}
                            </div>
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:right;font-size:xx-small">
                            所持金:{%$money%}元<br />
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:center;">
                            <img src="{%$staticUrl%}/apps/restaurant/mobile/img/item/{%$item.id%}.gif" />
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:center;font-size:xx-small">
                            {%$item.name%}<br />
                            {% if $paytype == 1%}
                            値段:{%$item.price%}ﾍﾞｸﾄﾙ<br />
                            {% else %}
                            値段:{%$item.mprice%}point<br />
                            {% /if %}
                            {%$item.description%}
                        </div>
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/green_line.gif" width="100%" height="2px" style="margin-top:3px;margin-bottom:3px" />
                        <div style="text-align:center;font-size:xx-small">
                            <a href='{% "$baseUrl/shop/buyitem/itemId/`$item.id`/CF_pay/`$paytype`"|mixiurl %}'>買う</a> <a href='{% "$baseUrl/shop/item"|mixiurl %}'>ｼｮｯﾌﾟに戻る</a>
                        </div>
                        <table><tr><td></td></tr></table>
                </div><!--/#menu_list-->
        </div>
</div>

{%include file="footer.phtml"%}