{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div class="label">
                        <div style="background:#69ac16;text-align:center;font-size:xx-small;color:#FFF">
                                ｼｮｯﾌﾟ一覧
                        </div>
                </div>
                <table><tr><td></td></tr></table>
                <div class="shop_menu" style="text-align:center;font-size:xx-small">
                        <div style="text-align:center;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/dotted.gif" width="240px" height="1px" style="margin-top:3px;margin-bottom:3px;" />
                        </div>
                        <a href='{% "$baseUrl/shop/item/CF_type/1/CF_pay/`$paytype`"|mixiurl %}'>時短ｱｲﾃﾑ</a>/<a href='{% "$baseUrl/shop/item/CF_type/2/CF_pay/`$paytype`"|mixiurl %}'>増加ｱｲﾃﾑ</a>/<a href='{% "$baseUrl/shop/item/CF_type/3/CF_pay/`$paytype`"|mixiurl %}'>ﾚｼﾋﾟ本</a>/<a href='{% "$baseUrl/shop/item/CF_type/4/CF_pay/`$paytype`"|mixiurl %}'>まかない</a>
                        <div style="text-align:center;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/dotted.gif" width="240px" height="1px" style="margin-top:3px;margin-bottom:3px;" />
                        </div>
                        <div style="text-align:center;font-size:xx-small">
                                [<a href='{% "$baseUrl/shop/item/CF_type/`$type`/CF_pay/1"|mixiurl %}'>通常ｱｲﾃﾑ</a>/<a href='{% "$baseUrl/shop/item/CF_type/`$type`/CF_pay/2"|mixiurl %}'>課金ｱｲﾃﾑ</a>]
                        </div>
                </div>
                <div style="text-align:right;font-size:xx-small">
                        所持金:{%$money%}元<br />
                </div>
                <table><tr><td></td></tr></table>
                <div id="deco_list">
                    {% foreach from=$item item=shopItem %}
                    <div style="text-align:left;margin:auto;width:240px">
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/item/{%$shopItem.id%}.gif" style="float:left;margin-right:5px" align="left" />
                        {%$shopItem.name%}<br />
                        {% if $paytype == 1%}
                        値段:{%$shopItem.price%}ﾍﾞｸﾄﾙ<br />
                        {% else %}
                        値段:{%$shopItem.mprice%}point<br />
                        {% /if %}
                        現在の所持数:{%$shopItem.count%}個<br />
                        <div style="clear:both" clear="all">
                            {%$shopItem.description%}
                        </div>
                        <div style="text-align:right;">
                            <a href='{% "$baseUrl/shop/itemconfirm/itemId/`$shopItem.id`/CF_pay/`$paytype`"|mixiurl %}'>購入する</a>
                        </div>
                    </div>
                    <img src="{%$staticUrl%}/apps/restaurant/mobile/img/green_line.gif" width="100%" height="2px" style="margin-top:3px;margin-bottom:3px" />
                    {% /foreach %}
                    
                    {%include file="common/pager.phtml"%}
                </div>
                <table><tr><td></td></tr></table>
                </div><!--/#shop_list-->
        </div>
</div>

{%include file="footer.phtml"%}