{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div id="item_detail">
                        <div class="label">
                                <div style="background:#69ac16;text-align:center;font-size:xx-small;color:#FFF">
                                        {% $nbItem.name %}
                                </div>
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:center;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/decoration/14.gif" />
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:center;font-size:xx-small">
                                {% $nbItem.description %}
                        </div>
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/green_line.gif" width="100%" height="2px" style="margin-top:3px;margin-bottom:3px" />
                        <div style="text-align:center;font-size:xx-small">
                                <a href="use_item.php">使う</a> <a href='{% "$baseUrl/mobile/item/itemlist?CF_type=`$nbItem.type`"|mixiurl %}'>戻る</a>
                        </div>
                        <table><tr><td></td></tr></table>
                </div><!--/#menu_list-->
        </div>
</div>

{%include file="footer.phtml"%}
