    <div id="footer" style="background:#d7efa5;font-size:xx-small">
        <div style="background:#69ac16;text-align:center;font-size:x-small;color:#FFF">
                メニュー
        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/label_line.gif" width="100%" height="10px" />
        </div>
        <table><tr><td></td></tr></table>
        <div class="menu" style="font-size:xx-small">
                <a href='{% "$baseUrl/mobile/recipe/recipelist"|mixiurl %}'>レシピ</a>:今まで覚えたﾚｼﾋﾟ<br />
                <a href='{% "$baseUrl/shop"|mixiurl %}'>アｲﾃム</a>:もっているｱｲﾃﾑ<br />
                <a href="help.php">ヘルプ</a>:わからなくなったらｺｺで
        </div>
        <table><tr><td></td></tr></table>
        <div id="main_controll">
                {% emoji code="F987" %}<a href='{% "$baseUrl/mobile/restaurant/index"|mixiurl %}' accesskey="1">ｷｯﾁﾝに戻る</a>
        </div>

		<div id="mixiFooter">
			<img src="{%$staticUrl%}/apps/restaurant/mobile/img/spacer.gif" width="1" height="2" /><br />
			<div class="headline" style="background:#eee;text-align:center;">
				{% emoji code="F990" %}<a href="#">ﾎｰﾑ</a><br />
			</div><!--/.headline-->
			<span style="color:#f93;">◆</span>ｻﾎﾟｰﾄﾒﾆｭｰ<br />
			<span style="color:#f93;">├</span><a href="#">ご利用上の注意事項</a><br />
			<span style="color:#f93;">├</span><a href="#">ﾍﾙﾌﾟ</a><span style="color:#f93;">/</span><a href="#">お問い合わせ･通報</a><br />
			<span style="color:#f93;">└</span><a href="#">ﾛｸﾞｱｳﾄ</a><br />
			<img src="{%$staticUrl%}/apps/restaurant/mobile/img/spacer.gif" width="1" height="5" /><br />
			<div id="copyright" style="background:#ff9933;text-align:center;">
				<span style="color:#fff;">(C)mixi,Inc.</span>
			</div><!--/#copyright-->
		</div><!--/#mixiFooter-->
    </div><!--/#footer-->

</body>
</html>