<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" lang="ja">
<head>
{% if $ua!=1 %}
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
{% else %}
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=Shift_JIS" />
{% /if %}
    <meta http-equiv="Content-Style-Type" content="text/css" />
	<title>{% $_appName %} - mixiｱﾌﾟﾘ</title>
	<style type="text/css">
		<![CDATA[
			a:link{color:#00b3e0;}
			a:visited{color:#bd5000;}
			a:focus{}
			*{
				font-size:xx-small;
				color:#392007;
			}
		]]>
	</style>
</head>
<body style="color:#666;font-size:x-small;background:#ffe">
