{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div style="background:#69ac16;text-align:center;font-size:xx-small;color:#FFF">
                        お出かけで料理研究
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/label_line.gif" width="100%" height="10px" />
                </div>
                <table><tr><td></td></tr></table>
                <div id="friend_list">
                        <div style="font-size:x-small;background:#f6f6f6;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/h.gif" width="5px" height="17px" style="float:left;margin-right:2px" align="left" />
                                ﾏｲﾐｸの店舗
                                <div style="clear:both;" clear="all">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/line.gif" width="100%" height="1px" />
                                </div>
                        </div>
                        <table><tr><td></td></tr></table>
                        {% foreach from=$friendList item=friend %}
                        <div style="text-align:left;font-size:xx-small">
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/character/{%$friend.character%}.gif" style="float:left;margin-right:5px" align="left" />
                                {%$friend.displayName%}(Lv.{%$friend.level%})<br />
                                <span style="color:#2da9d3">
                                {%$friend.speech%}
                                </span>
                                <table><tr><td></td></tr></table>
                                <div style="text-align:left;float:right;" align="right">
                                        <a href='{% "$baseUrl/mobile/restaurant/friend?CF_uid=`$friend.uid`"|mixiurl %}'>料理を食べに行く</a>
                                </div>
                                <div style="clear:both" clear="all">
                                <table><tr><td></td></tr></table>
                                </div>
                        </div>
                        {% /foreach %}

                        {%include file="common/pager.phtml"%}

                        <table><tr><td></td></tr></table>
                </div><!--/#menu_list-->
        </div>
</div>

{%include file="footer.phtml"%}
