{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div id="menu_list">
                        <div style="font-size:x-small;background:#f6f6f6;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/h.gif" width="5px" height="17px" style="float:left;margin-right:2px" align="left" />
                                本日のメニュー
                                <div style="clear:both;" clear="all">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/line.gif" width="100%" height="1px" />
                                </div>
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-aling:left;font-size:xx-small;width:240px;margin:auto">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/0_6_sum.gif" width="30px" height="30px" style="float:left;margin-right:5px;" align="left" />
                                設定した今日のﾒﾆｭｰはｻﾗﾀﾞとﾘｿﾞｯﾄね。OLや大学生の女の子たちに人気がありそうね。
                        </div>
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/green_line.gif" width="100%" height="2px" style="margin-top:3px;margin-bottom:3px" />
                        <div style="text-align:center;font-size:x-small">
                                <a href='{% "$baseUrl/flash/cookcomplete/CF_food/`$food`"|mixiurl %}'>これでOK！</a>
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:left;font-size:xx-small">
                                ・ｻﾗﾀﾞ　[<a href='{% "$baseUrl/restaurant/menulist"|mixiurl %}'>変更する</a>]<br />
                                ・ﾘｿﾞｯﾄ　[<a href='{% "$baseUrl/restaurant/menulist"|mixiurl %}'>変更する</a>]
                        </div>
                        <table><tr><td></td></tr></table>



                </div><!--/#menu_list-->
        </div>
</div>

{%include file="footer.phtml"%}