{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div id="comment">
                        <div style="font-size:x-small;background:#f6f6f6;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/h.gif" width="5px" height="17px" style="float:left;margin-right:2px" align="left" />
                                歓迎ﾒｯｾｰｼﾞ
                                <div style="clear:both;" clear="all">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/line.gif" width="100%" height="1px" />
                                </div>
                        </div>
                        <table><tr><td></td></tr></table>
                        <div class="form" style="text-align:center;font-size:xx-small">
                            <form method="post" action='{% "$baseUrl/mobile/restaurant/patroncommentconfirm"|mixiurl %}'>
                                <input type="text" name="CF_comment" id="CF_comment" value="{%$comment%}" size="20" maxlength="20" />
                                <input type="hidden" name="CF_hid_comment" id="CF_hid_comment" value="{%$comment%}" />
                                <input type="hidden" name="CF_fid" id="CF_fid" value="{%$fid%}" />
                                <input type="submit" value="コメント" />
                            </form>

                        </div><!--/.comment-->
                        <table><tr><td></td></tr></table>
                        <div style="text-align:center;font-size:xx-small">
                                <a href='{% "$baseUrl/mobile/restaurant/patronlist"|mixiurl %}'>戻る</a>
                        </div>
                </div>
        </div><!--/#body-->
</div><!--/#continar-->

{%include file="footer.phtml"%}
