{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div style="background:#69ac16;text-align:center;font-size:xx-small;color:#FFF">
                        お出かけで料理研究
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/label_line.gif" width="100%" height="10px" />
                </div>
                <table><tr><td></td></tr></table>
                <div id="friend_list">
                        <div style="font-size:x-small;background:#f6f6f6;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/h.gif" width="5px" height="17px" style="float:left;margin-right:2px" align="left" />
                                ﾏｲﾐｸの店舗
                                <div style="clear:both;" clear="all">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/line.gif" width="100%" height="1px" />
                                </div>
                        </div>
                        <table><tr><td></td></tr></table>
                        {% foreach from=$friendList item=user %}
                            <div style="text-align:left;font-size:xx-small">
                                    <img src="{%$staticUrl%}/apps/restaurant/mobile/img/character/{%$user.character%}.gif" width="30" style="float:left;margin-right:5px" align="left" />
                                   {%$user.displayName%}(Lv.{%$user.level%})<br />
                                    <span style="color:#2da9d3">
                                    歓迎ﾒｯｾｰｼﾞ:{%$user.comment|unescape_emoji%} <a href='{% "$baseUrl/mobile/restaurant/patroncomment?CF_fid=`$user.uid`"|mixiurl %}'>編集</a>
                                    </span>
                                    <div style="clear:both" clear="all">
                                    <img src="{%$staticUrl%}/apps/restaurant/mobile/img/line.gif" width="100%" height="1px" style="margin-top:3px;margin-bottom:3px" />
                                    </div>
                            </div>
                        {% /foreach %}

                        {%include file="common/pager.phtml"%}

                        <table><tr><td></td></tr></table>
                </div><!--/#menu_list-->
        </div>
</div>

{%include file="footer.phtml"%}
