{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div id="comment">
                        <div style="font-size:x-small;background:#f6f6f6;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/h.gif" width="5px" height="17px" style="float:left;margin-right:2px" align="left" />
                                歓迎ﾒｯｾｰｼﾞ決定
                                <div style="clear:both;" clear="all">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/line.gif" width="100%" height="1px" />
                                </div>
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:left;font-size:xx-small">
                                歓迎ﾒｯｾｰｼﾞ:{%$comment%}
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:center;font-size:xx-small">
                                <a href='{% "$baseUrl/mobile/restaurant/patronlist"|mixiurl %}'>戻る</a>
                        </div>
                </div>
        </div><!--/#body-->
</div><!--/#continar-->

{%include file="footer.phtml"%}
