{%include file="header.phtml"%}

<div id="container">
        <div id="body">
                <div id="comment">
                        <div style="font-size:x-small;background:#f6f6f6;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/h.gif" width="5px" height="17px" style="float:left;margin-right:2px" align="left" />
                                歓迎ﾒｯｾｰｼﾞ確認
                                <div style="clear:both;" clear="all">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/line.gif" width="100%" height="1px" />
                                </div>
                        </div>
                        <table><tr><td></td></tr></table>
                        <div style="text-align:left;font-size:xx-small">
                                歓迎ﾒｯｾｰｼﾞ:{%$comment%}
                        </div>
                        <div style="text-align:center">
                                <form action='{% "$baseUrl/mobile/restaurant/patroncommentcomplete"|mixiurl %}' method="post">
                                    <input type="hidden" name="CF_comment" id="CF_comment" value="{%$comment%}" size="20" maxlength="20" />
                                    <input type="hidden" name="CF_hid_comment" id="CF_hid_comment" value="{%$hidComment%}" />
                                    <input type="hidden" name="CF_fid" id="CF_fid" value="{%$fid%}" />
                                    <input type="submit" value="決定" />
                                </form>
                        </div>
                        <table><tr><td></td></tr></table>

                </div>
        </div><!--/#body-->
</div><!--/#continar-->

{%include file="footer.phtml"%}
