{%include file="header.phtml"%}

<div id="container">
        <div id="header" style="text-align:center">
                <div class="label">
                        <div style="background:#69ac16;text-align:center;font-size:xx-small;color:#FFF">
                                <table><tr><td></td></tr></table>
                                超人気の穴場店
                                <table><tr><td></td></tr></table>
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/label_line.gif" width="100%" height="10px" />
                        </div>
                </div>
        </div>
        <div id="body">
                <div class="profile">
                        <table><tr><td></td></tr></table>
                        <img src="{%$staticUrl%}/apps/restaurant/mobile/img/character/{%$userPro.character%}.gif" style="float:left;margin-right:5px" align="left" />
                        <div style="font-size:xx-small">
                        レベル:{%$userPro.level%}<br />
                        経験値:{%$userPro.exp%}/{%$nbExp%}<br />
                        ﾚｼﾋﾟ数:{%$userPro.recipe_count%}<br />
                        常連客:<a href='{% "$baseUrl/mobile/restaurant/patronlist"|mixiurl %}'>{%$patronCount%}人</a><br />
                        行きつけ:{%$arriveCount%}店舗<br />
                        所持金:{%$userMoney%}<br />
                        <table><tr><td></td></tr></table>
                        </div>
                        <div style="clear:both" clear="all">
                                <table><tr><td></td></tr></table>
                        </div>
                        <div style="font-size:xx-small">
                                来店したお客様に一言！<br />
                            <form method="post" action='{% "$baseUrl/mobile/restaurant/editspeech"|mixiurl %}'>
                                └<input type="text" name="CF_speech" id="CF_speech" value="{% $userSpeech|unescape_emoji%}" maxlength="20"/><br />
                                <input type="hidden" name="CF_hid_speech" id="CF_hid_speech" value="{% $userSpeech|unescape_emoji%}"/>
                                <div style="text-align:left;">※最大20文字･絵文字可</div>
                                <div class="btn" style="text-align:center;">
                                    <input type="submit" value=" 編 集 " /><br />
                                </div><!--/.btn-->
                            </form>
                        </div>
                        <table><tr><td></td></tr></table>
                </div>
                <div id="friendguest">
                        <div style="font-size:x-small;background:#eee;">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/h.gif" width="5px" height="17px" style="float:left;margin-right:2px" align="left" />
                                来店履歴
                                <div style="clear:both;" clear="all">
                                <img src="{%$staticUrl%}/apps/restaurant/mobile/img/line.gif" width="100%" height="1px" />
                                </div>
                        </div>
                        <table><tr><td></td></tr></table>
                        <div class="feedlist">
                        {% if $userEatList %}
                            {% foreach from=$userEatList item=user%}
                                <div style="text-align:left;font-size:xx-small">
                                        <a href="friend.php">{%$user.displayName%}：{%$user.eat_count%}回食べにきた</a>
                                </div>
                            {% /foreach %}
                        {% else %}
                            まだ何もありません。
                        {% /if %}

                        </div><!--/.feedlist-->
                        <table><tr><td></td></tr></table>
                </div><!--/#friendguest-->
        </div><!--/#body-->
</div>

{%include file="footer.phtml"%}
